baseURL = 'https://matthewrowe.co.uk/'
languageCode = 'en-gb'
title = "Tutorials & PPTs: C#, Unity 2D, Winforms, MVC, ASP, H046, H446..."
theme = 'mainroad'
contentDir = 'content'
googleAnalytics = "G-WLRJGWNQ13"

#Include this if you want to see comments etc.
#[markup.goldmark.renderer] 
#unsafe = true

[services]
  [services.disqus]
    shortname = "@disqus_ENqqZyyZeH"

# MainRoad Theme settings #
paginate = "10" # Number of posts per page

[Params.logo]
  #image = "img/myface.jpg" # Logo image. Path relative to "static"
  title = "Matthew Rowe's Website" # Logo title, otherwise will use site title
  subtitle = "Easy to follow technical tutorials..." # Logo subtitle

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"

# Enable widgets in given order
widgets = ["search", "social", "taglist"]

[Params.widgets]
  recent_num = 8 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.thumbnail]
  visibility = ["list"] # Control thumbnail visibility set to list only so you don't see it in the main pages
  

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  github = "MatthewGRowe"
  email = "matt@matthewrowe.co.uk"
  linkedin = "mattict"

# Custom social links
[[Params.widgets.social.custom]]
  title = "𑥅YouTube"
  url = "https://www.youtube.com/channel/UCmG1_HQSkbXjr7skvOmBn2w"
  icon = "svg/youtube.svg" # Optional. Path relative to "layouts/partials"
  rel = false #"noopener noreferrer" # Set to false to remove the rel attribute

# Used in authorbox at the top of each page, need to add the 
# authorbox option in the page front matter "authorbox: true"
[Author] 
  name = "Matthew Rowe"
  #bio appears at the bottom of the page
  bio = "Matthew Rowe is a computing lecturer who writes accessible educational materials for use by anyone who wants to learn.  Feel free to contact me [matt@matthewrowe.co.uk](mailto:matt@matthewrowe.co.uk)"
  avatar = "/img/myface.jpg"

[Params]
  description = "Matthew Rowe's C#, Winforms, MVC, Unity tutorials.  H446/01, H446/02, H046/01, H046/02" # Site description. Used in meta description
  copyright = "Matthew Rowe" # Footer copyright holder, otherwise will use site title
  schema = true # Enable Schema
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true  # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["recent", "post", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02-01-2006" # Change the format of dates
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  #customCSS = ["css/custom.css"] # Include custom CSS files
  #customJS = ["js/custom.js"] # Include custom JS files


#Menu
[menus]
  [[menus.main]]
    name = 'Home' #Words on the menu
    pageRef = '/' #link to the folder
    weight = 10  #seems to dictate the order, higher=further right
  [[menus.main]]
    name = 'Winforms'
    pageRef = '/winforms'
    weight = 20
  [[menus.main]]
    name = 'Unity'
    pageRef = '/unity'
    weight = 30
  [[menus.main]]
    name = 'API/ASP/MVC'
    pageRef = '/api'
    weight = 40
  [[menus.main]]
    name = 'A-Level'
    pageRef = '/alevel'
    weight = 50
  [[menus.main]]
    name = 'HTML Guide'
    pageRef = '/html'
    weight = 60
  [[menus.main]]
    name = 'About Me'
    pageRef = 'about'
    weight = 70